apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foobar-api-certs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar-api
  labels:
    app: foobar-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar-api
  template:
    metadata:
      labels:
        app: foobar-api
    spec:
      volumes:
      - name: cert-volume
        persistentVolumeClaim:
          claimName: foobar-api-certs-pvc

      initContainers:
      - name: cert-gen
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add openssl;
            if [ ! -f /cert/cert.pem ]; then
              openssl req -x509 -newkey rsa:4096 -keyout /cert/key.pem -out /cert/cert.pem -days 365 -nodes -subj '/CN=foobar-api.local';
            else
              echo "Cert already exists";
            fi
        volumeMounts:
        - name: cert-volume
          mountPath: /cert

      containers:
      - name: foobar-api
        #image: fernandobenegasa/foobar-api
        image: local/foobar-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cert-volume
          mountPath: /cert
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: foobar-api-svc
spec:
  selector:
    app: foobar-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
